apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.users.conf: |
    input {
      jdbc { 
        jdbc_connection_string => "jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true"
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        # The user we wish to execute our statement as
        jdbc_user => "${DB_USER}"
        jdbc_password => "${DB_PASSWORD}"
        # our query
        schedule => "* * * * *"
        statement => "SELECT u.id, avatar, first_name, last_name, username, verified, created_at, zipcode FROM users u LEFT JOIN address a ON u.id = a.user_id WHERE created_at > :sql_last_value ORDER BY created_at;" 
        use_column_value => true
        tracking_column => "created_at"
        last_run_metadata_path => "$HOME/.logstash-users_jdbc_last_run"
      }
    }
    output {
      stdout { codec => json_lines }
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        index => "users"
        document_id => "%{id}"
        ecs_compatibility => v1
        cacert => "/etc/logstash/certificates/ca.crt"
      }
    }
  logstash.products.conf: |
    input {
      jdbc { 
        jdbc_connection_string => "jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true"
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        # The user we wish to execute our statement as
        jdbc_user => "${DB_USER}"
        jdbc_password => "${DB_PASSWORD}"
        # our query
        schedule => "* * * * *"
        statement => "SELECT product_id as id, p.name, description, image, price, shippable, creation_date_time as created_at, s.store_name FROM products p LEFT JOIN stores s ON p.product_id = s.store_id WHERE created_at > :sql_last_value ORDER BY created_at;"
        use_column_value => true
        tracking_column => "created_at" 
        last_run_metadata_path => "$HOME/.logstash-products_jdbc_last_run"
      }
    }
    output {
      stdout { codec => rubydebug }
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        index => "products"
        document_id => "%{id}"
        ecs_compatibility => v1
        cacert => "/etc/logstash/certificates/ca.crt"
      }
    }
